name = "gleam_synapses"
version = "1.0.0"
licences = ["Apache-2.0"]
description = "A plug-and-play library for neural networks written in Gleam"

[docs]
links = [
  { title = 'GitHub', href = 'https://github.com/mrdimosthenis/gleam_synapses' }
]

[repository]
type = "github"
user = "mrdimosthenis"
repo = "gleam_synapses"

[dependencies]
gleam_stdlib = "~> 0.21"
minigen = "~> 0.0"
gleam_zlists = "~> 0.0"
gleam_json = "~> 0.4"

[dev-dependencies]
gleeunit = "~> 0.6"
