name = "gleam_synapses"
version = "1.0.1"
licences = ["Apache-2.0"]
description = "A plug-and-play library for neural networks written in Gleam"

[docs]
links = [
  { title = 'GitHub', href = 'https://github.com/mrdimosthenis/gleam_synapses' }
]

[repository]
type = "github"
user = "mrdimosthenis"
repo = "gleam_synapses"

[dependencies]
gleam_stdlib = "~> 0.40.0"
minigen = "~> 0.1.1"
gleam_zlists = "~> 1.0.0"
gleam_json = "~> 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.2.0"
